# Generated by Django 3.0.4 on 2020-03-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d/')),
            ],
        ),
    ]
