# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Annotation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Annotation

  target 'AnnotationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnnotationUITests' do
    # Pods for testing
  end

end

pod 'Alamofire'